# Go Web Server Configuration

server:
  # Port to listen on
  port: "8080"

# The default virtual host if no specific domain matches the request's Host header
default_vhost:
  static_dir: "./static"
  fpm_network: ""
  fpm_address: ""

# You can define multiple domains (Virtual Hosts) here
vhosts:
  "example.local":
    static_dir: "./static_example"
    fpm_network: ""
    fpm_address: ""
